import { randomUuid } from '../js/core/identifiers.js';
import test from 'node:test';
import assert from 'node:assert/strict';
import { createDemoRepository, DEMO_STORAGE_KEY, DEMO_CUSTOMER_ID } from '../js/repositories/demo-repository.js';
import { createRepository } from '../js/repositories/repository-factory.js';
import { initialDemoState } from '../js/data/demo.js';
import { CONFIG } from '../js/config.js';
import { scopeOf, scopeKey, assertScope } from '../js/core/scope.js';
import { emptyCart, changeQuantity, quoteCart } from '../js/core/cart.js';
import { isPricePending, knownStock, isCommerciallyPurchasable } from '../js/core/commercial.js';
import { requireTransition, allowedActions } from '../js/core/workflow-policy.js';
function setup({seed=initialDemoState, storage:customStorage}={}){
  const values=new Map();const storage=customStorage||{getItem:k=>values.get(k)??null,setItem:(k,v)=>values.set(k,v)};
  let counter=0;const uuid=()=>`00000000-0000-4000-8000-${String(++counter).padStart(12,'0')}`;
  const repo=createDemoRepository({storage,uuid,locks:null,seed,clock:()=>new Date(1789444800000+counter*1000).toISOString()});
  return {repo,storage,values,uuid};
}
const actor=(repo,id='orilla')=>({kind:'merchant',...scopeOf(repo.business(id))});
const sampleCustomer={name:'Cliente de prueba',phone:'0000000000',address:'Calle de prueba 123',notes:''};
async function order(repo,businessId='orilla',fulfillment='pickup'){
  const productId=businessId==='orilla'?'burger-clasica':'pizza-muzza';
  await repo.setQuantity(businessId,productId,1);const requestId=await repo.prepareRequest(businessId);
  const command={businessId,requestId,lines:repo.cart(businessId).lines,fulfillment,customer:sampleCustomer};
  return {order:await repo.createOrder(command),command};
}
const code=expected=>error=>error.code===expected;

test('los carritos de dos comercios tienen claves distintas',()=>{const {repo}=setup();assert.notEqual(scopeKey(scopeOf(repo.business('orilla')),'cart'),scopeKey(scopeOf(repo.business('horno')),'cart'));});
test('la localidad participa del ámbito',()=>assert.throws(()=>assertScope({businessId:'orilla',localityId:'otra'},{businessId:'orilla',localityId:'alumine'}),code('TENANT_MISMATCH')));
test('identificadores inseguros no construyen claves',()=>assert.throws(()=>scopeKey({businessId:'../test',localityId:'alumine'},'cart'),code('INVALID_SCOPE')));
test('un producto ajeno no entra al carrito',async()=>{const {repo}=setup();await assert.rejects(repo.setQuantity('orilla','pizza-muzza',1),code('TENANT_MISMATCH'));});
test('dos carritos conservan su contenido separado',async()=>{const {repo}=setup();await repo.setQuantity('orilla','burger-clasica',1);await repo.setQuantity('horno','pizza-muzza',2);assert.equal(repo.cart('orilla').lines[0].quantity,1);assert.equal(repo.cart('horno').lines[0].quantity,2);});
test('el carrito persiste entre instancias',async()=>{const {repo,storage}=setup();await repo.setQuantity('orilla','papas',2);assert.equal(createDemoRepository({storage,locks:null}).cart('orilla').lines[0].quantity,2);});
for(const quantity of [-1,1.5,NaN,Infinity,'2',100])test(`rechaza cantidad inválida ${quantity}`,async()=>{const {repo}=setup();await assert.rejects(repo.setQuantity('orilla','papas',quantity),code('INVALID_QUANTITY'));});
test('cantidad cero elimina un producto',async()=>{const {repo}=setup();await repo.setQuantity('orilla','papas',1);await repo.setQuantity('orilla','papas',0);assert.equal(repo.cart('orilla').lines.length,0);});
for(const price of [null,undefined,'',0,-1,NaN,Infinity])test(`precio no comercial ${String(price)} bloqueado`,()=>assert.equal(isPricePending({price,priceStatus:'confirmed'}),true));
test('price_status pendiente prevalece sobre camelCase confirmado',()=>assert.equal(isPricePending({price:10,priceStatus:'confirmed',price_status:'pending'}),true));
test('stock desconocido no es stock cero',()=>{assert.equal(knownStock({stock:null}),null);assert.equal(knownStock({stock:0}),0);});
test('un producto archivado no es comprable',()=>assert.equal(isCommerciallyPurchasable({price:10,stock:1,available:true,archived:true}),false));
test('retirar no cobra envío',async()=>{const {repo}=setup();await repo.setQuantity('orilla','burger-clasica',1);const quote=repo.quote('orilla','pickup');assert.equal(quote.deliveryFee,0);assert.equal(quote.total,10500);});
test('delivery usa solo la tarifa del comercio',async()=>{const {repo}=setup();await repo.setQuantity('orilla','burger-clasica',1);const quote=repo.quote('orilla','delivery');assert.equal(quote.total,12000);});
test('pedido mínimo se calcula sobre los productos',async()=>{const {repo}=setup();await repo.setQuantity('orilla','papas',1);assert.throws(()=>repo.quote('orilla','delivery'),code('MINIMUM_ORDER'));});
test('un comercio cerrado no admite pedidos',async()=>{const {repo}=setup();await repo.setQuantity('orilla','burger-clasica',1);await repo.setBusinessOpen('orilla',false,actor(repo));assert.throws(()=>repo.quote('orilla'),code('BUSINESS_CLOSED'));});
test('se rechazan productos duplicados',()=>{const state=initialDemoState();const b=state.businesses[0];assert.throws(()=>quoteCart({...scopeOf(b),lines:[{productId:'papas',quantity:1},{productId:'papas',quantity:1}]},b,state.products),code('DUPLICATE_PRODUCT'));});
test('pedido descuenta stock y vacía solo su carrito',async()=>{const {repo}=setup();await repo.setQuantity('horno','pizza-muzza',1);await order(repo);assert.equal(repo.products('orilla').find(p=>p.id==='burger-clasica').stock,29);assert.equal(repo.cart('orilla').lines.length,0);assert.equal(repo.cart('horno').lines.length,1);});
test('reintento idempotente no crea ni descuenta dos veces',async()=>{const {repo}=setup();const original=await order(repo);const repeat=await repo.createOrder(original.command);assert.equal(repeat.id,original.order.id);assert.equal(repo.snapshot().orders.length,1);assert.equal(repo.products('orilla')[0].stock,29);});
test('misma clave y distinto payload se rechazan',async()=>{const {repo}=setup();const {command}=await order(repo);await assert.rejects(repo.createOrder({...command,customer:{...sampleCustomer,name:'Otro ejemplo'}}),code('IDEMPOTENCY_CONFLICT'));});
test('la clave de pedido es durable',async()=>{const {repo,storage}=setup();await repo.setQuantity('orilla','papas',1);const id=await repo.prepareRequest('orilla');const second=createDemoRepository({storage,locks:null});assert.equal(await second.prepareRequest('orilla'),id);});
test('modificar cantidades invalida el intento anterior',async()=>{const {repo}=setup();await repo.setQuantity('orilla','papas',1);const id=await repo.prepareRequest('orilla');await repo.setQuantity('orilla','papas',2);assert.notEqual(await repo.prepareRequest('orilla'),id);});
test('se ignora un precio falsificado en el comando del cliente',async()=>{const {repo}=setup();await repo.setQuantity('orilla','burger-clasica',1);const requestId=await repo.prepareRequest('orilla');const result=await repo.createOrder({businessId:'orilla',requestId,lines:[{productId:'burger-clasica',quantity:1,unitPrice:1}],fulfillment:'pickup',customer:sampleCustomer});assert.equal(result.total,10500);});
test('una línea de otro comercio se rechaza al crear pedido',async()=>{const {repo,uuid}=setup();await assert.rejects(repo.createOrder({businessId:'orilla',requestId:uuid(),lines:[{productId:'pizza-muzza',quantity:1}],fulfillment:'pickup',customer:sampleCustomer}),code('TENANT_MISMATCH'));});
test('pedido delivery exige dirección',async()=>{const {repo,uuid}=setup();await assert.rejects(repo.createOrder({businessId:'orilla',requestId:uuid(),lines:[{productId:'burger-clasica',quantity:1}],fulfillment:'delivery',customer:{...sampleCustomer,address:''}}),code('ADDRESS_REQUIRED'));});
test('Mercado Pago permanece bloqueado en el repositorio',async()=>{const {repo,uuid}=setup();await assert.rejects(repo.createOrder({businessId:'orilla',requestId:uuid(),lines:[{productId:'papas',quantity:1}],fulfillment:'pickup',customer:sampleCustomer,paymentMethod:'mercadopago'}),code('PAYMENTS_DISABLED'));});
test('no hay fallback de producción hacia demo',()=>{assert.throws(()=>createRepository({...CONFIG,mode:'production'},{}),code('PRODUCTION_NOT_IMPLEMENTED'));assert.throws(()=>createRepository({...CONFIG,livePayments:true},{}),code('PRODUCTION_NOT_IMPLEMENTED'));});
test('el panel de un comercio no enumera pedidos de otro',async()=>{const {repo}=setup();await order(repo);await order(repo,'horno');assert.equal(repo.orders(actor(repo)).length,1);assert.equal(repo.orders(actor(repo))[0].businessId,'orilla');});
test('un comercio no modifica pedidos ajenos',async()=>{const {repo}=setup();const {order:o}=await order(repo);await assert.rejects(repo.transition({orderId:o.id,expectedVersion:o.version,nextStatus:'accepted',actor:actor(repo,'horno')}),code('TRANSITION_FORBIDDEN'));});
test('estado desconocido no se normaliza a uno autorizado',()=>assert.throws(()=>requireTransition({status:'desconocido'},'accepted',{kind:'merchant'}),code('INVALID_STATUS')));
test('el flujo de retiro no entra a reparto',async()=>{const {repo}=setup();let {order:o}=await order(repo);for(const s of ['accepted','preparing','ready'])o=await repo.transition({orderId:o.id,expectedVersion:o.version,nextStatus:s,actor:actor(repo)});assert.deepEqual(allowedActions(o,actor(repo)),['delivered','canceled']);await assert.rejects(repo.transition({orderId:o.id,expectedVersion:o.version,nextStatus:'assigned',actor:actor(repo),riderId:'rider-orilla'}),code('TRANSITION_FORBIDDEN'));});
test('circuito completo de delivery con repartidor propio',async()=>{const {repo}=setup();let {order:o}=await order(repo,'orilla','delivery');for(const s of ['accepted','preparing','ready','assigned'])o=await repo.transition({orderId:o.id,expectedVersion:o.version,nextStatus:s,actor:actor(repo),riderId:'rider-orilla'});const rider={kind:'rider',id:'rider-orilla',...scopeOf(repo.business('orilla'))};for(const s of ['picked_up','on_the_way','arrived','delivered'])o=await repo.transition({orderId:o.id,expectedVersion:o.version,nextStatus:s,actor:rider});assert.equal(o.status,'delivered');assert.equal(o.history.length,9);});
test('no se asigna un rider de otro comercio',async()=>{const {repo}=setup();let {order:o}=await order(repo,'orilla','delivery');for(const s of ['accepted','preparing','ready'])o=await repo.transition({orderId:o.id,expectedVersion:o.version,nextStatus:s,actor:actor(repo)});await assert.rejects(repo.transition({orderId:o.id,expectedVersion:o.version,nextStatus:'assigned',actor:actor(repo),riderId:'rider-horno'}),code('TENANT_MISMATCH'));});
test('una versión de pedido obsoleta no sobreescribe el estado',async()=>{const {repo}=setup();const {order:o}=await order(repo);await repo.transition({orderId:o.id,expectedVersion:1,nextStatus:'accepted',actor:actor(repo)});await assert.rejects(repo.transition({orderId:o.id,expectedVersion:1,nextStatus:'preparing',actor:actor(repo)}),code('STALE_ORDER'));});
test('cancelar devuelve stock una única vez',async()=>{const {repo}=setup();const {order:o}=await order(repo);await repo.transition({orderId:o.id,expectedVersion:1,nextStatus:'canceled',actor:{kind:'customer',id:DEMO_CUSTOMER_ID}});assert.equal(repo.products('orilla')[0].stock,30);await assert.rejects(repo.transition({orderId:o.id,expectedVersion:2,nextStatus:'canceled',actor:actor(repo)}),code('TRANSITION_FORBIDDEN'));assert.equal(repo.products('orilla')[0].stock,30);});
test('no se cambia el propietario de un producto mediante patch',async()=>{const {repo}=setup();await assert.rejects(repo.updateProduct('orilla','papas',{businessId:'horno'},actor(repo)),code('FIELD_FORBIDDEN'));});
test('el comercio no cambia precios ajenos',async()=>{const {repo}=setup();await assert.rejects(repo.updateProduct('orilla','pizza-muzza',{price:1},actor(repo)),code('TENANT_MISMATCH'));});
test('editar precio actualiza la cotización',async()=>{const {repo}=setup();await repo.setQuantity('orilla','papas',1);await repo.updateProduct('orilla','papas',{price:6000},actor(repo));assert.equal(repo.quote('orilla').total,6000);});
test('fallo de escritura no se presenta como guardado',async()=>{const storage={getItem:()=>null,setItem:()=>{throw new Error('quota');}};const {repo}=setup({storage});await assert.rejects(repo.setQuantity('orilla','papas',1),code('STORAGE_WRITE_FAILED'));});
test('datos corruptos no se borran silenciosamente',()=>{const {repo,values}=setup();values.set(DEMO_STORAGE_KEY,'broken');assert.throws(()=>repo.snapshot(),code('CORRUPT_STORAGE'));assert.equal(values.get(DEMO_STORAGE_KEY),'broken');});
test('dos pedidos simultáneos no sobrevenden en la misma instancia demo',async()=>{const seed=()=>{const s=initialDemoState();s.products.find(p=>p.id==='papas').stock=1;return s;};const {repo,uuid}=setup({seed});const command={businessId:'orilla',lines:[{productId:'papas',quantity:1}],fulfillment:'pickup',customer:sampleCustomer};const results=await Promise.allSettled([repo.createOrder({...command,requestId:uuid()}),repo.createOrder({...command,requestId:uuid()})]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal(repo.products('orilla').find(p=>p.id==='papas').stock,0);});
test('devolver snapshots no permite mutar la base sin guardar',()=>{const {repo}=setup();const state=repo.snapshot();state.businesses[0].name='alterado';assert.equal(repo.business('orilla').name,'La Orilla');});

test('UUID alternativo usa aleatoriedad criptográfica y bits v4',()=>{assert.match(randomUuid({getRandomValues:bytes=>bytes.fill(9)}),/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/);});
test('sin fuente segura no se generan identificadores débiles',()=>assert.throws(()=>randomUuid({}),code('CRYPTO_UNAVAILABLE')));
